name: Publish

on: release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Publish
      run: npm run dist
